import { useState, useEffect, useRef } from 'react';
import { DndContext, PointerSensor, KeyboardSensor, useSensor, useSensors, closestCenter, useDroppable, useDraggable, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, useSortable, sortableKeyboardCoordinates, rectSortingStrategy, arrayMove } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ArrowLeft, ArrowUp, ArrowDown, Plus, Search, Undo2, Redo2, Copy, Trash2, GripVertical, Save, Eye, Code2, Check, History, Layers, Settings2, ChevronRight, PanelRightClose } from 'lucide-react';
import { catalog, makeField, flatten, updateField, removeField, cloneField } from '../shared/definition';
import type { Field, FormRecord, FormDefinition, Rule } from '../shared/types';
import { api, download } from './api';
import { FieldPreview } from './FieldPreview';
import { AdvancedFieldOptions } from './AdvancedFieldOptions';

import { Modal, Setting, Section, Toggle } from './ui';
import { FormSettings, FeedSettings } from './FormSettings';

type BuilderProps = { form: FormRecord; onSaved: (form: FormRecord) => void; onBack: () => void; onEntries: () => void; notify: (text: string, error?: boolean) => void };
function findParent(fields: Field[], id: string): Field[] | undefined { if (fields.some(f => f.id === id)) return fields; for (const f of fields) { const found = findParent(f.children, id); if (found) return found; } }
function insertAfter(fields: Field[], id: string, item: Field): Field[] { return fields.flatMap(f => f.id === id ? [f, item] : [{ ...f, children: insertAfter(f.children, id, item) }]); }
function replaceSiblings(fields: Field[], target: Field[], replacement: Field[]): Field[] { if (fields === target) return replacement; return fields.map(f => ({ ...f, children: replaceSiblings(f.children, target, replacement) })); }

function SortableField({ field, selected, select, edit, children }: { field: Field; selected: boolean; select: () => void; edit: (action: string) => void; children?: React.ReactNode }) {
  const sortable = useSortable({ id: field.id });
  return <div ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition, gridColumn: `span ${field.width}`, opacity: sortable.isDragging ? .4 : 1 }} className={`canvas-field ${selected ? 'selected' : ''} ${children ? 'canvas-container' : ''}`} onClick={e => { e.stopPropagation(); select(); }} tabIndex={0} role="group" aria-label={`${field.label} field`} onKeyDown={e => { if (e.key === 'Enter') select(); }}>
    <div className="field-controls"><button className="drag-handle" {...sortable.attributes} {...sortable.listeners} aria-label={`Move ${field.label}`}><GripVertical size={14} /></button><span>{field.type}</span><div /><button aria-label={`Move ${field.label} up`} onClick={e => { e.stopPropagation(); edit('up'); }}><ArrowUp size={13} /></button><button aria-label={`Move ${field.label} down`} onClick={e => { e.stopPropagation(); edit('down'); }}><ArrowDown size={13} /></button><button aria-label={`Duplicate ${field.label}`} onClick={e => { e.stopPropagation(); edit('duplicate'); }}><Copy size={13} /></button><button aria-label={`Delete ${field.label}`} onClick={e => { e.stopPropagation(); edit('delete'); }}><Trash2 size={13} /></button></div>
    {children || <FieldPreview field={field} />}
  </div>;
}

export function Builder({ form, onSaved, onBack, onEntries, notify }: BuilderProps) {
  const [record, setRecord] = useState(form); const [history, setHistory] = useState<FormDefinition[]>([structuredClone(form.definition)]); const [position, setPosition] = useState(0);
  const [selected, setSelected] = useState(''); const [panel, setPanel] = useState('fields'); const [tab, setTab] = useState('editor'); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false); const [embed, setEmbed] = useState(false); const [revisions, setRevisions] = useState<{ id: number; version: number; created_at: string }[] | null>(null); const [viewport, setViewport] = useState('desktop');
  const definition = history[position]; const current = flatten(definition.fields).find(f => f.id === selected); const dirty = JSON.stringify(definition) !== JSON.stringify(record.definition) || record.title !== form.title || record.status !== form.status;
  const latest = useRef({ definition, record, dirty }); latest.current = { definition, record, dirty };
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  function change(next: FormDefinition) { setHistory(prev => [...prev.slice(0, position + 1), next].slice(-100)); setPosition(Math.min(position + 1, 99)); }
  function fields(next: Field[]) { change({ ...definition, fields: next }); }
  function changeField(patch: Partial<Field>) { if (current) fields(updateField(definition.fields, current.id, f => ({ ...f, ...patch }))); }
  function add(type: string) { const field = makeField(type); if (current && catalog.find(c => c.type === current.type)?.container) fields(updateField(definition.fields, current.id, f => ({ ...f, children: [...f.children, field] }))); else fields([...definition.fields, field]); setSelected(field.id); setPanel('customize'); }
  function action(field: Field, what: string) {
    if (what === 'delete') { fields(removeField(definition.fields, field.id)); if (selected === field.id) setSelected(''); }
    else if (what === 'duplicate') { const copy = cloneField(field); fields(insertAfter(definition.fields, field.id, copy)); setSelected(copy.id); }
    else { const siblings = findParent(definition.fields, field.id); if (!siblings) return; const index = siblings.findIndex(f => f.id === field.id); const next = index + (what === 'up' ? -1 : 1); if (next >= 0 && next < siblings.length) fields(replaceSiblings(definition.fields, siblings, arrayMove(siblings, index, next))); }
  }
  function dragEnd({ active, over }: DragEndEvent) {
    if (!over || active.id === over.id) return;
    const palette = String(active.id).startsWith('palette-');
    const dragged = palette ? makeField(String(active.id).slice(8)) : flatten(definition.fields).find(f => f.id === active.id); if (!dragged) return;
    const parent = findParent(definition.fields, String(active.id)); const otherParent = findParent(definition.fields, String(over.id));
    if (!palette && parent && parent === otherParent) { fields(replaceSiblings(definition.fields, parent, arrayMove(parent, parent.findIndex(f => f.id === active.id), parent.findIndex(f => f.id === over.id)))); return; }
    if (String(over.id).startsWith('drop-')) {
      const containerId = String(over.id).slice(5); if (flatten([dragged]).some(f => f.id === containerId)) return;
      const without = palette ? definition.fields : removeField(definition.fields, dragged.id); fields(containerId === 'root' ? [...without, dragged] : updateField(without, containerId, f => ({ ...f, children: [...f.children, dragged] })));
    } else if (otherParent && !flatten([dragged]).some(f => f.id === over.id)) {
      const without = palette ? definition.fields : removeField(definition.fields, dragged.id);
      const insert = (items: Field[]): Field[] => items.flatMap(f => f.id === over.id ? [dragged, f] : [{ ...f, children: insert(f.children) }]);
      fields(insert(without));
    }
    setSelected(dragged.id);
  }
  async function save() {
    setSaving(true);
    try { const result = await api<FormRecord>(`forms/${record.id}`, 'PUT', { ...latest.current.record, definition: latest.current.definition }); setRecord(result); onSaved(result); notify('Form saved.'); return result; } catch (error) { notify((error as Error).message, true); } finally { setSaving(false); }
  }
  useEffect(() => {
    const handler = (event: BeforeUnloadEvent) => { if (latest.current.dirty) event.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler);
  }, []);
  function renderFields(items: Field[]) {
    return <SortableContext items={items.map(f => f.id)} strategy={rectSortingStrategy}><div className="canvas-fields">{items.map(field => <SortableField key={field.id} field={field} selected={selected === field.id} select={() => { setSelected(field.id); setPanel('customize'); }} edit={what => action(field, what)}>{catalog.find(c => c.type === field.type)?.container ? <div className="container-inner"><div className="container-label"><Layers size={14} />{field.label}</div>{renderFields(field.children)}<DropArea id={field.id} empty={!field.children.length} onClick={() => { setSelected(field.id); setPanel('fields'); }} /></div> : null}</SortableField>)}</div></SortableContext>;
  }
  const short = `[gitpress_form id="${record.id}"]`;
  return <>
    <div className="builder-heading"><div className="builder-title"><button className="icon-button" onClick={onBack} aria-label="Back to forms"><ArrowLeft size={19} /></button><div><input aria-label="Form title" value={record.title} onChange={e => setRecord({ ...record, title: e.target.value })} /><small>Form #{record.id}<span>•</span>{dirty ? 'Unsaved changes' : 'All changes saved'}</small></div></div><div className="button-row"><select aria-label="Form status" value={record.status} onChange={e => setRecord({ ...record, status: e.target.value as FormRecord['status'] })}><option value="draft">Draft</option><option value="published">Published</option><option value="trash">Trash</option></select><button onClick={() => setEmbed(true)}><Code2 size={15} />Embed</button><button onClick={() => { const url = new URL(window.GitPressFormsAdmin.site); url.searchParams.set('gpf_preview', String(record.id)); url.searchParams.set('_wpnonce', window.GitPressFormsAdmin.nonce); window.open(url, '_blank', 'noopener'); }}><Eye size={15} />Preview</button><button className="primary" disabled={saving} onClick={save}><Save size={15} />{saving ? 'Saving…' : 'Save Form'}</button></div></div>
    <div className="editor-navigation"><nav aria-label="Form sections">{[['editor', 'Editor'], ['settings', 'Settings & Integrations'], ['style', 'Design']].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}<button onClick={onEntries}>Entries</button></nav><span className="shortcode-mini">{short}<button aria-label="Copy shortcode" onClick={() => { navigator.clipboard.writeText(short).then(() => notify('Shortcode copied.')); }}><Copy size={13} /></button></span></div>
    {tab === 'editor' ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><div className="builder-workspace"><div className="builder-canvas-area"><div className="canvas-toolbar"><div className="button-row"><button className="icon-button" disabled={position === 0} onClick={() => setPosition(position - 1)} aria-label="Undo"><Undo2 size={17} /></button><button className="icon-button" disabled={position === history.length - 1} onClick={() => setPosition(position + 1)} aria-label="Redo"><Redo2 size={17} /></button><span className="toolbar-divider" /><button className="icon-button" aria-label="Version history" onClick={() => api<{ id: number; version: number; created_at: string }[]>(`forms/${record.id}/revisions`).then(setRevisions).catch(e => notify(e.message, true))}><History size={17} /></button></div><div className="viewport-switch">{['desktop', 'tablet', 'mobile'].map(size => <button key={size} className={viewport === size ? 'active' : ''} onClick={() => setViewport(size)}>{size}</button>)}</div><span>{flatten(definition.fields).length} fields</span></div><div className={`canvas-paper viewport-${viewport}`} style={{ '--preview-primary': definition.style.primary, '--preview-radius': `${definition.style.radius}px` } as React.CSSProperties}>{renderFields(definition.fields)}<DropArea id="root" empty={!definition.fields.length} onClick={() => { setSelected(''); setPanel('fields'); }} /><div className="canvas-submit"><span style={{ background: definition.style.primary }}>{definition.settings.submitLabel}</span></div></div><div className="canvas-hint">Click a field to customize it. Drag the handle or use the arrow controls to reorder.</div></div>
    <aside className="builder-sidebar"><div className="sidebar-tabs"><button className={panel === 'fields' ? 'active' : ''} onClick={() => setPanel('fields')}><Plus size={15} />Input Fields</button><button className={panel === 'customize' ? 'active' : ''} onClick={() => setPanel('customize')}><Settings2 size={15} />Input Customization</button><button onClick={() => api<{ id: number; version: number; created_at: string }[]>(`forms/${record.id}/revisions`).then(setRevisions).catch(e => notify(e.message, true))}>History</button></div>{panel === 'fields' ? <div className="field-palette"><div className="search-box"><Search size={16} /><input placeholder="Search input fields" value={search} onChange={e => setSearch(e.target.value)} /></div>{current && catalog.find(c => c.type === current.type)?.container ? <p className="insert-context">Adding to: {current.label}<button onClick={() => setSelected('')}>Clear</button></p> : null}{['General', 'Advanced', 'Layout'].map(group => <Section key={group} title={`${group} Fields`} open={group === 'General' || search !== ''}><div className="palette-grid">{catalog.filter(f => f.group === group && f.label.toLowerCase().includes(search.toLowerCase())).map(field => <PaletteField key={field.type} type={field.type} label={field.label} onAdd={() => add(field.type)} />)}</div></Section>)}</div> : current ? <div className="customization"><div className="customize-title">{catalog.find(c => c.type === current.type)?.label}<code>{current.name}</code></div><Section title="Basic Options"><Setting label="Element Label"><input value={current.label} onChange={e => changeField({ label: e.target.value })} /></Setting><Setting label="Name Attribute" help="Unique key used in conditions, notifications, and exports."><input value={current.name} onChange={e => changeField({ name: e.target.value })} /></Setting><Setting label="Placeholder"><input value={current.placeholder} onChange={e => changeField({ placeholder: e.target.value })} /></Setting><Toggle label="Required" checked={current.required} onChange={required => changeField({ required })} /><Setting label="Help Message"><textarea rows={2} value={current.help} onChange={e => changeField({ help: e.target.value })} /></Setting></Section>
    <Section title="Advanced Options"><Setting label="Default Value" help="Supports {query:parameter} and {user.email}."><input value={current.default} onChange={e => changeField({ default: e.target.value })} /></Setting><Setting label="Field Width"><select value={current.width} onChange={e => changeField({ width: Number(e.target.value) })}>{[[12, 'Full width'], [6, 'One half'], [4, 'One third'], [3, 'One quarter']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Setting><Toggle label="Unique value" checked={!!current.unique} onChange={unique => changeField({ unique })} />{['number', 'slider', 'rating', 'nps'].includes(current.type) ? <div className="two-columns"><Setting label="Minimum"><input type="number" value={current.min ?? ''} onChange={e => changeField({ min: e.target.value === '' ? undefined : Number(e.target.value) })} /></Setting><Setting label="Maximum"><input type="number" value={current.max ?? ''} onChange={e => changeField({ max: e.target.value === '' ? undefined : Number(e.target.value) })} /></Setting></div> : null}{current.type === 'calculation' ? <Setting label="Formula" help="Use {field_name}, + − * / %, min, max, round, abs, sum."><textarea value={current.formula || ''} onChange={e => changeField({ formula: e.target.value })} /></Setting> : null}{current.type === 'html' ? <Setting label="HTML Content"><textarea className="code-input" rows={6} value={current.html || ''} onChange={e => changeField({ html: e.target.value })} /></Setting> : null}{['file', 'image'].includes(current.type) ? <Setting label="Allowed Extensions"><input value={current.accept || '.pdf,.jpg,.png'} onChange={e => changeField({ accept: e.target.value })} /></Setting> : null}{['select', 'radio', 'checkbox', 'multiselect', 'ranking', 'grid'].includes(current.type) ? <Setting label="Choices" help="One choice per line. Use Label | value to set a separate value."><textarea rows={5} value={current.options.map(o => `${o.label} | ${o.value}`).join('\n')} onChange={e => changeField({ options: e.target.value.split('\n').map(line => { const [label, value] = line.split('|'); return { label: label.trim(), value: (value ?? label).trim() }; }) })} /></Setting> : null}{current.type === 'grid' ? <Setting label="Rows"><textarea value={(current.rows || []).join('\n')} onChange={e => changeField({ rows: e.target.value.split('\n') })} /></Setting> : null}</Section><Section title="Field Behavior"><AdvancedFieldOptions field={current} onChange={changeField} /></Section><Section title="Conditional Logic"><ConditionEditor value={current.condition} onChange={condition => changeField({ condition })} fields={flatten(definition.fields).filter(f => f.id !== current.id)} /></Section></div> : <div className="sidebar-empty"><Settings2 size={28} /><p>Select a field in the form to customize its options.</p></div>}</aside></div></DndContext> : null}
    {tab === 'settings' ? <FormSettings definition={definition} onChange={change} formId={record.id} notify={notify} /> : null}
    {tab === 'style' ? <div className="design-layout"><div className="settings-card"><h2>Form Design</h2><p>Set the appearance of every field in this form.</p>{(['primary', 'text', 'background', 'border'] as const).map(key => <Setting label={key.charAt(0).toUpperCase() + key.slice(1)} key={key}><div className="color-control"><input type="color" value={definition.style[key]} onChange={e => change({ ...definition, style: { ...definition.style, [key]: e.target.value } })} /><code>{definition.style[key]}</code></div></Setting>)}{(['radius', 'gap', 'fontSize', 'maxWidth'] as const).map(key => <Setting key={key} label={{ radius: 'Border radius', gap: 'Field spacing', fontSize: 'Font size', maxWidth: 'Maximum width' }[key]}><input type="number" value={definition.style[key]} onChange={e => change({ ...definition, style: { ...definition.style, [key]: Number(e.target.value) } })} /></Setting>)}<Setting label="Label Position"><select value={definition.style.labelPosition} onChange={e => change({ ...definition, style: { ...definition.style, labelPosition: e.target.value as 'top' | 'left' } })}><option value="top">Above field</option><option value="left">Left of field</option></select></Setting><button onClick={() => download('gitpress-form-style.json', definition.style)}>Export Style</button><label className="file-button">Import Style<input type="file" accept=".json" onChange={async e => { try { if (e.target.files?.[0]) { const style = JSON.parse(await e.target.files[0].text()); change({ ...definition, style: { ...definition.style, ...style } }); } } catch { notify('Invalid style file.', true); } }} /></label></div><div className="design-preview"><h3>Live design preview</h3><div className="design-sample" style={{ color: definition.style.text, background: definition.style.background, fontSize: definition.style.fontSize, borderRadius: definition.style.radius, '--preview-primary': definition.style.primary, '--preview-radius': `${definition.style.radius}px` } as React.CSSProperties}>{flatten(definition.fields).filter(f => !f.children.length).slice(0, 4).map(f => <div key={f.id} style={{ marginBottom: definition.style.gap }}><FieldPreview field={f} /></div>)}<button style={{ background: definition.style.primary, color: '#fff', borderRadius: definition.style.radius }}>{definition.settings.submitLabel}</button></div></div></div> : null}
    <Modal title="Embed your form" open={embed} onOpenChange={setEmbed}><p>Paste this shortcode into WordPress or a GitPress HTML fragment.</p><div className="copy-code"><code>{short}</code><button onClick={() => navigator.clipboard.writeText(short).then(() => notify('Shortcode copied.'))}><Copy size={16} />Copy</button></div><p>Or use the <strong>GitPress Form</strong> block in the WordPress editor.</p><a href={`${window.GitPressFormsAdmin.site}?gitpress_form=${record.id}`} target="_blank" rel="noreferrer">Open the published landing page <ChevronRight size={13} /></a><p className="muted">Publish and save the form before embedding it.</p></Modal>
    <Modal title="Version history" open={revisions !== null} onOpenChange={open => { if (!open) setRevisions(null); }}>{revisions?.map(revision => <div className="revision-row" key={revision.id}><div><strong>Version {revision.version}</strong><small>{revision.created_at} UTC</small></div><button onClick={async () => { try { const restored = await api<FormRecord>(`forms/${record.id}/revisions/${revision.id}`, 'POST', {}); setRecord(restored); setHistory([restored.definition]); setPosition(0); onSaved(restored); setRevisions(null); notify('Revision restored as a new version.'); } catch (error) { notify((error as Error).message, true); } }}>Restore</button></div>)}</Modal>
  </>;
}
function DropArea({ id, empty, onClick }: { id: string; empty: boolean; onClick: () => void }) { const { setNodeRef, isOver } = useDroppable({ id: `drop-${id}` }); return <button ref={setNodeRef} className={`canvas-drop ${empty ? 'empty' : ''} ${isOver ? 'drag-over' : ''}`} onClick={onClick}><Plus size={empty ? 24 : 16} />{empty ? <><strong>{id === 'root' ? 'Start building your form' : 'Add fields to this container'}</strong><span>Choose an input field from the right panel</span></> : <span>Add a field</span>}</button>; }
function FieldIcon({ type }: { type: string }) { const text: Record<string, string> = { email: '@', number: '#', textarea: '☰', name: 'Aa', text: 'T', phone: '☎', url: '↗', date: '▦', checkbox: '☑', radio: '◉', select: '⌄', file: '↑', image: '▧', container: '▥', step: '⇥', calculation: 'ƒ', rating: '☆', color: '◐', signature: '✎' }; return <span className="palette-icon">{text[type] || '▤'}</span>; }
export function ConditionEditor({ value, onChange, fields }: { value?: Rule; onChange: (rule: Rule | undefined) => void; fields: Field[] }) {
  return <><Toggle label="Enable conditional logic" checked={!!value?.rules.length} onChange={enabled => onChange(enabled ? { mode: 'all', rules: [{ field: fields[0]?.name || '', operator: 'eq', value: '' }] } : undefined)} />{value?.rules.length ? <><Setting label="Match"><select value={value.mode} onChange={e => onChange({ ...value, mode: e.target.value as 'all' | 'any' })}><option value="all">All of these rules</option><option value="any">Any of these rules</option></select></Setting>{value.rules.map((rule, index) => <div className="condition-row" key={index}><select aria-label="Condition field" value={rule.field} onChange={e => onChange({ ...value, rules: value.rules.map((r, i) => i === index ? { ...r, field: e.target.value } : r) })}>{fields.map(field => <option key={field.id} value={field.name}>{field.label}</option>)}</select><select aria-label="Condition operator" value={rule.operator} onChange={e => onChange({ ...value, rules: value.rules.map((r, i) => i === index ? { ...r, operator: e.target.value as typeof rule.operator } : r) })}>{['eq', 'neq', 'contains', 'gt', 'gte', 'lt', 'lte', 'empty', 'not_empty'].map(op => <option key={op} value={op}>{({ eq: 'Equals', neq: 'Not equals', contains: 'Contains', gt: 'Greater than', gte: 'At least', lt: 'Less than', lte: 'At most', empty: 'Is empty', not_empty: 'Is not empty' })[op]}</option>)}</select><input aria-label="Condition value" value={rule.value} onChange={e => onChange({ ...value, rules: value.rules.map((r, i) => i === index ? { ...r, value: e.target.value } : r) })} /><button className="icon-button" aria-label="Remove condition" onClick={() => onChange({ ...value, rules: value.rules.filter((_, i) => i !== index) })}><Trash2 size={14} /></button></div>)}<button onClick={() => onChange({ ...value, rules: [...value.rules, { field: fields[0]?.name || '', operator: 'eq', value: '' }] })}><Plus size={14} />Add rule</button></> : null}</>;
}

function PaletteField({ type, label, onAdd }: { type: string; label: string; onAdd: () => void }) {
  const drag = useDraggable({ id: `palette-${type}` });
  return <button ref={drag.setNodeRef} {...drag.attributes} {...drag.listeners} onClick={onAdd} aria-label={`Add ${label}`}><FieldIcon type={type} /><span>{label}</span></button>;
}
