import type { FormDefinition } from '../shared/types';
import { Setting, Toggle } from './ui';
export function DocumentSettings({ settings, onChange }: { settings: FormDefinition['settings']; onChange: (patch: Partial<FormDefinition['settings']>) => void }) {
  const pdf = settings.pdf || { title: '', intro: '', footer: '', paper: 'A4' as const };
  const view = settings.entryView || { enabled: false, restricted: true, intro: '', background: '#f5f7fb' };
  return <>
    <div className="settings-card"><h2>PDF Documents</h2><p>Download a PDF from each entry, or attach it to an email notification.</p><Setting label="Document Title" help="Leave blank to use the form title."><input value={pdf.title} onChange={e => onChange({ pdf: { ...pdf, title: e.target.value } })} /></Setting><Setting label="Introduction" help="Use {field_name} to include submitted values."><textarea value={pdf.intro} onChange={e => onChange({ pdf: { ...pdf, intro: e.target.value } })} /></Setting><Setting label="Footer"><textarea value={pdf.footer} onChange={e => onChange({ pdf: { ...pdf, footer: e.target.value } })} /></Setting><Setting label="Paper Size"><select value={pdf.paper} onChange={e => onChange({ pdf: { ...pdf, paper: e.target.value as 'A4' | 'letter' } })}><option value="A4">A4</option><option value="letter">US Letter</option></select></Setting></div>
    <div className="settings-card"><h2>Frontend Entry View</h2><Toggle label="Show a private entry link after submission" checked={view.enabled} onChange={enabled => onChange({ entryView: { ...view, enabled } })} />{view.enabled ? <><Toggle label="Require the submitter or an entry manager to sign in" help="When disabled, anyone with the private link can view the entry. Links expire after one year. Entry pages are excluded from search indexing." checked={view.restricted} onChange={restricted => onChange({ entryView: { ...view, restricted } })} /><Setting label="Entry Introduction"><textarea value={view.intro} onChange={e => onChange({ entryView: { ...view, intro: e.target.value } })} /></Setting><Setting label="Page Background"><input type="color" value={view.background} onChange={e => onChange({ entryView: { ...view, background: e.target.value } })} /></Setting></> : null}</div>
  </>;
}
