import { useEffect, useState } from 'react';
import { Search, Download, ChevronLeft, ChevronRight, FileText, Printer, Send } from 'lucide-react';
import type { Entry, FormRecord } from '../shared/types';
import { api, download } from './api';
import { Modal, Empty, Loading, Setting } from './ui';
import { EntryHistory } from './EntryHistory';
type Result = { items: Entry[]; total: number; page: number };
export function Entries({ forms, initialForm = 0, notify }: { forms: FormRecord[]; initialForm?: number; notify: (message: string, error?: boolean) => void }) {
  const [formId, setFormId] = useState(initialForm); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [result, setResult] = useState<Result | null>(null); const [active, setActive] = useState<Entry | null>(null); const [note, setNote] = useState(''); const [revision, setRevision] = useState(0); const [files, setFiles] = useState<{ id: number; original_name: string; url: string }[]>([]); const [edit, setEdit] = useState('');
  useEffect(() => { let alive = true; const timer = setTimeout(() => { api<Result>(`entries?form=${formId}&status=${encodeURIComponent(status)}&search=${encodeURIComponent(search)}&page=${page}`).then(r => { if (alive) setResult(r); }).catch(e => notify(e.message, true)); }, 180); return () => { alive = false; clearTimeout(timer); }; }, [formId, status, search, page, revision, notify]);
  async function open(entry: Entry) { setActive(entry); setEdit(JSON.stringify(entry.response, null, 2)); setNote(''); try { setFiles(await api(`entries/${entry.id}/files`)); } catch { setFiles([]); } }
  async function update(body: object) { if (!active) return; try { const entry = await api<Entry>(`entries/${active.id}`, 'PUT', { ...body, version: active.version }); setActive(entry); setRevision(r => r + 1); setNote(''); notify('Entry updated.'); } catch (error) { notify((error as Error).message, true); } }
  async function exportEntries(format: 'csv' | 'json') {
    const all: Entry[] = []; let p = 1;
    try { while (true) { const data = await api<Result>(`entries?form=${formId}&status=${encodeURIComponent(status)}&search=${encodeURIComponent(search)}&page=${p}`); all.push(...data.items); if (all.length >= data.total || !data.items.length) break; p++; } if (format === 'json') download('gitpress-entries.json', all); else {
      const keys = [...new Set(all.flatMap(e => Object.keys(e.response)))];
      const escape = (value: unknown) => { let text = typeof value === 'object' && value !== null ? JSON.stringify(value) : String(value ?? ''); if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"`; };
      download('gitpress-entries.csv', [['id', 'form_id', 'status', 'created_at', ...keys], ...all.map(e => [e.id, e.form_id, e.status, e.created_at, ...keys.map(k => e.response[k] ?? '')])].map(row => row.map(escape).join(',')).join('\r\n'), 'text/csv');
    } } catch (error) { notify((error as Error).message, true); }
  }
  return <div className="page-content"><div className="page-heading"><div><h1>All Entries</h1><p>Every conversation starts here. Review and manage your submissions.</p></div><div className="button-row"><button onClick={() => exportEntries('csv')}><Download size={16} />Export CSV</button><button onClick={() => exportEntries('json')}>JSON</button></div></div><div className="table-card"><div className="table-toolbar"><div className="button-row"><select aria-label="Filter by form" value={formId} onChange={e => { setFormId(Number(e.target.value)); setPage(1); }}><option value={0}>All Forms</option>{forms.map(f => <option key={f.id} value={f.id}>{f.title}</option>)}</select><select aria-label="Entry status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All Statuses</option>{['partial', 'unread', 'read', 'pending_approval', 'pending_confirmation', 'approved', 'rejected', 'spam', 'trash'].map(s => <option key={s} value={s}>{s.replaceAll('_', ' ')}</option>)}</select></div><div className="search-box"><Search size={16} /><input aria-label="Search entries" placeholder="Search entries…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div></div>{!result ? <Loading /> : result.items.length ? <><table className="data-table"><thead><tr><th>Entry</th><th>Form</th><th>Submission</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>{result.items.map(entry => <tr key={entry.id}><td><button className="text-button" onClick={() => open(entry)}>#{entry.id}</button></td><td>{forms.find(f => f.id === entry.form_id)?.title || `Form #${entry.form_id}`}</td><td className="entry-summary">{Object.values(entry.response).filter(v => typeof v === 'string' || typeof v === 'number').slice(0, 2).join(' · ') || 'View submission'}</td><td><span className={`badge ${entry.status === 'unread' ? 'blue' : ''}`}>{entry.status.replaceAll('_', ' ')}</span></td><td className="muted">{entry.created_at.slice(0, 16)}</td><td><button className="icon-button" onClick={() => open(entry)} aria-label={`View entry ${entry.id}`}><ChevronRight size={16} /></button></td></tr>)}</tbody></table><div className="pagination"><span>{result.total} entries</span><div className="button-row"><button disabled={page === 1} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft size={16} /></button><span>Page {page}</span><button disabled={page * 50 >= result.total} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight size={16} /></button></div></div></> : <Empty title="No entries yet">Submissions will appear here when someone completes a published form.</Empty>}</div>
  <Modal title={`Entry #${active?.id || ''}`} open={!!active} onOpenChange={open => { if (!open) setActive(null); }} wide>{active ? <><div className="entry-detail-meta"><span>{active.created_at} UTC</span><div className="button-row"><select disabled={!window.GitPressFormsAdmin.canEditEntries} value={active.status} aria-label="Update status" onChange={e => update({ status: e.target.value })}>{['unread', 'read', 'pending_approval', 'pending_confirmation', 'approved', 'rejected', 'spam', 'trash'].map(s => <option key={s} value={s} disabled={s.startsWith('pending_')}>{s.replaceAll('_', ' ')}</option>)}</select><button onClick={() => window.print()}><Printer size={15} />Print</button><button onClick={() => api<{ url: string }>(`entries/${active.id}/pdf`).then(result => { window.location.assign(result.url); }).catch(e => notify(e.message, true))}><Download size={15} />PDF</button></div></div><dl className="entry-details">{Object.entries(active.response).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{typeof value === 'object' ? <pre>{JSON.stringify(value, null, 2)}</pre> : String(value)}</dd></div>)}</dl>{files.length ? <div className="sub-card"><h3>Attachments</h3>{files.map(file => <a className="attachment-link" key={file.id} href={file.url}><FileText size={16} />{file.original_name}</a>)}</div> : null}{window.GitPressFormsAdmin.canEditEntries ? <details className="sub-card"><summary>Edit submitted values</summary><textarea className="code-input" rows={8} value={edit} onChange={e => setEdit(e.target.value)} /><button onClick={() => { try { update({ response: JSON.parse(edit) }); } catch { notify('Enter valid JSON.', true); } }}>Save Changes</button></details> : null}<EntryHistory entryId={active.id} version={active.version} /><h3>Notes</h3>{active.notes.map((n, i) => <div className="entry-note" key={i}><p>{n.body}</p><small>{n.at} · User #{n.by}</small></div>)}{window.GitPressFormsAdmin.canEditEntries ? <><Setting label="Add a Note"><textarea rows={2} value={note} onChange={e => setNote(e.target.value)} /></Setting><button disabled={!note.trim()} onClick={() => update({ note })}><Send size={14} />Add Note</button></> : null}</> : null}</Modal></div>;
}
