import { useState, useEffect } from 'react';
import { Plus, Trash2, Mail, Settings2, Code2, Plug, ShieldCheck, Workflow } from 'lucide-react';
import type { FormDefinition, Notification, Rule } from '../shared/types';
import { flatten, newId } from '../shared/definition';
import { Setting, Toggle, Empty } from './ui';
import { ConditionEditor } from './Builder';
import { api } from './api';
import { FormAccess } from './Permissions';
import { DocumentSettings } from './DocumentSettings';
export type Integration = { id: string; name: string; category: string; description: string; connected: boolean; credentials: Record<string, string>; fields: Record<string, string> };
type Props = { definition: FormDefinition; onChange: (value: FormDefinition) => void; formId: number; notify: (text: string, error?: boolean) => void };
export function FormSettings({ definition, onChange, formId, notify }: Props) {
  const [section, setSection] = useState('general'); const settings = definition.settings;
  function set(patch: Partial<typeof settings>) { onChange({ ...definition, settings: { ...settings, ...patch } }); }
  function notification(index: number, patch: Partial<Notification>) { set({ notifications: settings.notifications.map((n, i) => i === index ? { ...n, ...patch } : n) }); }
  return <div className="form-settings-layout"><nav className="settings-sidebar">{[['general', 'Form Settings', Settings2], ['notifications', 'Email Notifications', Mail], ['confirmation', 'Confirmations', Workflow], ['restrictions', 'Restrictions & Privacy', ShieldCheck], ['documents', 'PDF & Entry View', Mail], ['integrations', 'Integrations', Plug], ['code', 'Custom CSS / JS', Code2]].map(([id, label, Icon]) => { const Symbol = Icon as typeof Mail; return <button key={id as string} className={section === id ? 'active' : ''} onClick={() => setSection(id as string)}><Symbol size={17} />{label as string}</button>; })}</nav><div className="form-settings-content">
    {section === 'general' ? <div className="settings-card"><h2>Form Settings</h2><p>Customize the form experience and submission behavior.</p><Setting label="Submit Button Text"><input value={settings.submitLabel} onChange={e => set({ submitLabel: e.target.value })} /></Setting><Setting label="Form Experience"><select value={settings.mode} onChange={e => set({ mode: e.target.value as 'standard' | 'conversational' })}><option value="standard">Standard form</option><option value="conversational">Conversational · one question at a time</option></select></Setting><Toggle label="Save & Resume" help="Give visitors a private link to continue within 30 days." checked={settings.saveResume} onChange={saveResume => set({ saveResume })} /><Toggle label="Capture partial entries at each step" help="Save incomplete multi-step responses in Entries. No notifications or integrations run until final submission." checked={!!settings.trackPartial} onChange={trackPartial => set({ trackPartial })} /><Toggle label="Admin Approval" help="Hold integrations and notifications until an administrator approves an entry." checked={settings.approval} onChange={approval => set({ approval })} /><Toggle label="Double Opt-in" help="Require email confirmation before processing the entry. Add an email field to the form." checked={settings.doubleOptin} onChange={doubleOptin => set({ doubleOptin })} /></div> : null}
    {section === 'notifications' ? <><div className="section-heading"><div><h2>Email Notifications</h2><p>Route notifications using field values and conditions.</p></div><button className="primary" onClick={() => set({ notifications: [...settings.notifications, { id: newId(), to: '', subject: 'New form submission', message: '{all_fields}' }] })}><Plus size={15} />Add Notification</button></div>{!settings.notifications.length ? <Empty title="Keep the right people in the loop">Add a notification for your team or a confirmation email for visitors.</Empty> : settings.notifications.map((n, index) => <div className="settings-card" key={n.id}><div className="section-heading"><h3>Notification {index + 1}</h3><button className="icon-button danger" aria-label="Delete notification" onClick={() => set({ notifications: settings.notifications.filter((_, i) => i !== index) })}><Trash2 size={16} /></button></div><Setting label="Send To" help="Enter an email address, comma-separated addresses, or {email_field_name}."><input value={n.to} onChange={e => notification(index, { to: e.target.value })} /></Setting>{([['cc', 'CC'], ['bcc', 'BCC'], ['replyTo', 'Reply-To']] as const).map(([key, label]) => <Setting key={key} label={label}><input value={n[key] || ''} onChange={e => notification(index, { [key]: e.target.value })} /></Setting>)}<Setting label="Email Subject"><input value={n.subject} onChange={e => notification(index, { subject: e.target.value })} /></Setting><Setting label="Message" help="Use {all_fields} or {field_name} to include submitted values."><textarea rows={7} value={n.message} onChange={e => notification(index, { message: e.target.value })} /></Setting><Toggle label="Attach entry PDF" checked={!!n.attachPdf} onChange={attachPdf => notification(index, { attachPdf })} /><ConditionEditor value={n.condition} onChange={condition => notification(index, { condition })} fields={flatten(definition.fields)} /></div>)}</> : null}
    {section === 'confirmation' ? <div className="settings-card"><h2>Confirmation Settings</h2><p>Choose what visitors see after a successful submission.</p><Setting label="Confirmation Message"><textarea rows={4} value={settings.confirmation} onChange={e => set({ confirmation: e.target.value })} /></Setting><Setting label="Redirect URL" help="Optional. Leave blank to show the confirmation message."><input type="url" value={settings.redirect} onChange={e => set({ redirect: e.target.value })} /></Setting><h3>Conditional Confirmations</h3>{settings.confirmations.map((confirmation, i) => <div className="sub-card" key={i}><ConditionEditor value={confirmation.condition} onChange={condition => set({ confirmations: settings.confirmations.map((c, index) => index === i ? { ...c, condition: condition || { mode: 'all', rules: [] } } : c) })} fields={flatten(definition.fields)} /><Setting label="Message"><textarea value={confirmation.message} onChange={e => set({ confirmations: settings.confirmations.map((c, index) => index === i ? { ...c, message: e.target.value } : c) })} /></Setting><Setting label="Redirect URL"><input value={confirmation.redirect} onChange={e => set({ confirmations: settings.confirmations.map((c, index) => index === i ? { ...c, redirect: e.target.value } : c) })} /></Setting><button className="danger" onClick={() => set({ confirmations: settings.confirmations.filter((_, index) => i !== index) })}>Remove</button></div>)}<button onClick={() => set({ confirmations: [...settings.confirmations, { condition: { mode: 'all', rules: [] }, message: '', redirect: '' }] })}><Plus size={14} />Add Confirmation</button></div> : null}
    {section === 'restrictions' ? <div className="settings-card"><h2>Restrictions & Privacy</h2><p>Control availability and how long submissions are retained.</p><Toggle label="Require Login" checked={settings.requireLogin} onChange={requireLogin => set({ requireLogin })} /><Setting label="Maximum Entries" help="0 means no limit. Spam and trashed entries do not count."><input type="number" min={0} value={settings.maxEntries} onChange={e => set({ maxEntries: Number(e.target.value) })} /></Setting><div className="two-columns"><Setting label="Opens At (UTC)"><input type="datetime-local" value={settings.opensAt} onChange={e => set({ opensAt: e.target.value })} /></Setting><Setting label="Closes At (UTC)"><input type="datetime-local" value={settings.closesAt} onChange={e => set({ closesAt: e.target.value })} /></Setting></div><Setting label="Delete Entries After (Days)" help="0 retains entries indefinitely. Automatic deletion also removes attachments and delivery logs."><input type="number" min={0} value={settings.retentionDays} onChange={e => set({ retentionDays: Number(e.target.value) })} /></Setting><FormAccess value={settings.access} onChange={access => set({ access })} /><div className="info-note">Honeypot protection, server validation, and submission rate limits are always active.</div></div> : null}
    {section === 'documents' ? <DocumentSettings settings={settings} onChange={set} /> : null}
    {section === 'integrations' ? <FeedSettings formId={formId} definition={definition} notify={notify} /> : null}
    {section === 'code' ? <div className="settings-card"><h2>Custom CSS / JavaScript</h2><p>These settings require WordPress unfiltered_html permission.</p><Setting label="Custom CSS" help="Scope your selectors to .gpf-form to avoid changing the theme."><textarea className="code-input" rows={10} value={settings.css} onChange={e => set({ css: e.target.value })} /></Setting><Setting label="Custom JavaScript" help="The form element is available as the variable form."><textarea className="code-input" rows={10} value={settings.js} onChange={e => set({ js: e.target.value })} /></Setting></div> : null}
    </div></div>;
}
type Feed = { id: number; title: string; provider: string; configuration: { mapping: Record<string, string>; condition?: Rule }; enabled: number };
export function FeedSettings({ formId, definition, notify }: { formId: number; definition: FormDefinition; notify: Props['notify'] }) {
  const [providers, setProviders] = useState<Integration[]>([]); const [feeds, setFeeds] = useState<Feed[]>([]); const [editing, setEditing] = useState(0); const [condition, setCondition] = useState<Rule>(); const [provider, setProvider] = useState(''); const [mapping, setMapping] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false);
  useEffect(() => { let alive = true; Promise.all([api<Integration[]>('integrations'), api<Feed[]>(`forms/${formId}/feeds`)]).then(([p, f]) => { if (alive) { setProviders(p); setFeeds(f); } }).catch(e => notify(e.message, true)); return () => { alive = false; }; }, [formId, notify]);
  const selected = providers.find(p => p.id === provider);
  return <><div className="section-heading"><div><h2>Form Integrations</h2><p>Send accepted submissions to connected tools.</p></div></div>{feeds.map(feed => <div className="feed-row" key={feed.id}><span className="integration-avatar">{feed.title.slice(0, 1)}</span><div><strong>{feed.title}</strong><small>{feed.provider}</small></div><span className="badge">{feed.enabled ? 'Enabled' : 'Disabled'}</span><button onClick={() => { setEditing(feed.id); setProvider(feed.provider); setMapping(feed.configuration.mapping); setCondition(feed.configuration.condition); }}>Edit</button><button onClick={() => api(`feeds/${feed.id}`, 'PUT', { ...feed, enabled: !feed.enabled }).then(() => api<Feed[]>(`forms/${formId}/feeds`)).then(setFeeds).catch(e => notify(e.message, true))}>{feed.enabled ? 'Disable' : 'Enable'}</button><button className="icon-button danger" aria-label={`Delete ${feed.title}`} onClick={() => api(`feeds/${feed.id}`, 'DELETE').then(() => setFeeds(feeds.filter(f => f.id !== feed.id))).catch(e => notify(e.message, true))}><Trash2 size={16} /></button></div>)}<div className="settings-card"><h3>{editing ? 'Edit Integration Feed' : 'Add Integration Feed'}</h3><Setting label="Integration"><select value={provider} onChange={e => { setProvider(e.target.value); setMapping({}); }}><option value="">Choose a connected integration</option>{providers.filter(p => p.connected).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Setting>{selected ? <>{Object.entries(selected.fields).map(([key, label]) => <Setting key={key} label={label}><input list={`fields-${formId}`} value={mapping[key] || ''} onChange={e => setMapping({ ...mapping, [key]: e.target.value })} /></Setting>)}<datalist id={`fields-${formId}`}>{flatten(definition.fields).map(f => <option key={f.id} value={`{${f.name}}`}>{f.label}</option>)}<option value="{all_fields}">All submitted fields</option></datalist><ConditionEditor fields={flatten(definition.fields)} value={condition} onChange={setCondition} /><p className="muted">Map fields with {'{field_name}'} or enter a fixed value. Feeds are saved separately from the form.</p><button className="primary" disabled={busy} onClick={async () => { setBusy(true); try { await api(editing ? `feeds/${editing}` : `forms/${formId}/feeds`, editing ? 'PUT' : 'POST', { provider, title: selected.name, enabled: true, configuration: { mapping, condition } }); setFeeds(await api<Feed[]>(`forms/${formId}/feeds`)); setProvider(''); setEditing(0); setCondition(undefined); notify('Integration feed saved.'); } catch (error) { notify((error as Error).message, true); } finally { setBusy(false); } }}><Plus size={15} />{editing ? 'Save Feed' : 'Add Feed'}</button></> : <p className="muted">Configure your accounts in the Integrations screen first.</p>}</div></>;
}
